### PR TITLE
Logos updated to svg version

### PR DESCRIPTION
**Pull request by JoWProDev**
**Add space for ...**  
  
Etherscan: https://viewblock.io/zilliqa/address/zil1pdxm02u4v6wmjtwswqm305uyth2lkwurawkvre
CoinGecko: N/A 
Website: https://tokentalks.carrd.co/
Twitter: https://twitter.com/TokenTalksTT

### CODE REVIEW

**Review by Annihilatopia — APPROVED** [review]

**Comment by JoWProDev** [comment]
Is there anything else that needs to be done? I have noticed the website does not show new projects after they were merged into master.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Annihilatopia** [comment]
It does show up, we've just haven't pushed them to production yet. I'll get the greenlight to push to production and you should see the new projects @evesnow91 let me know when greenlit, thanks.

**Comment by Annihilatopia** [comment]
And it's up on production! @JoWProDev

**Comment by JoWProDev** [comment]
Yep, I see it there now! Great. Thank You!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
